### ISSUE TITLE
Please, update dependencies

### ISSUE THREAD

**Issue by IluhinDotPro** [moazelsawaf/dash_flags#1]
Because every version of dash_flags depends on flutter_svg ^1.1.6 and ***** depends on flutter_svg ^2.0.0+1, dash_flags is forbidden.
So, because *** depends on dash_flags ^0.0.3, version solving failed.
pub get failed

**Comment by moazelsawaf** [comment]
Upgraded and officially released to pub.dev 💙
Thanks for helping out 🙏🏻💙
